_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
batch_size:
    value: 128
dataset:
    value: MNIST
epochs:
    value: 10
model:
    value: MLP
random_seed:
    value: 42
randomize_percent:
    value: 1
